# Generated by Django 5.2.4 on 2025-07-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dt_inclusao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
