# Generated by Django 5.2.4 on 2025-07-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0004_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='dt_inclusao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
