# Generated by Django 5.2.4 on 2025-07-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0006_alter_operacao_dt_inclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='dt_inclusao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
